package src.main.java.booking;
// Generated Oct 1, 2019, 11:56:01 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;

/**
 * AdminUserSession generated by hbm2java
 */
public class AdminUserSession implements java.io.Serializable {

	private Integer sessionId;
	private int userId;
	private String token;
	private Date lastmodified;
	private Date cretatedate;
	private Integer isdeleted;

	public AdminUserSession() {
	}

	public AdminUserSession(int userId, String token) {
		this.userId = userId;
		this.token = token;
	}

	public AdminUserSession(int userId, String token, Date lastmodified, Date cretatedate, Integer isdeleted) {
		this.userId = userId;
		this.token = token;
		this.lastmodified = lastmodified;
		this.cretatedate = cretatedate;
		this.isdeleted = isdeleted;
	}

	public Integer getSessionId() {
		return this.sessionId;
	}

	public void setSessionId(Integer sessionId) {
		this.sessionId = sessionId;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public String getToken() {
		return this.token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	public Date getLastmodified() {
		return this.lastmodified;
	}

	public void setLastmodified(Date lastmodified) {
		this.lastmodified = lastmodified;
	}

	public Date getCretatedate() {
		return this.cretatedate;
	}

	public void setCretatedate(Date cretatedate) {
		this.cretatedate = cretatedate;
	}

	public Integer getIsdeleted() {
		return this.isdeleted;
	}

	public void setIsdeleted(Integer isdeleted) {
		this.isdeleted = isdeleted;
	}

}
