package src.main.java.booking;
// Generated Oct 5, 2019, 3:25:22 PM by Hibernate Tools 5.4.3.Final

import java.util.Date;

/**
 * AdminUserRole generated by hbm2java
 */
public class AdminUserRole implements java.io.Serializable {

	private Integer userRoleId;
	private String userRoleName;
	private String userRoleDescription;
	private Integer createby;
	private Date cretatedate;
	private Integer isdeleted;

	public AdminUserRole() {
	}

	public AdminUserRole(String userRoleName, String userRoleDescription) {
		this.userRoleName = userRoleName;
		this.userRoleDescription = userRoleDescription;
	}

	public AdminUserRole(String userRoleName, String userRoleDescription, Integer createby, Date cretatedate,
			Integer isdeleted) {
		this.userRoleName = userRoleName;
		this.userRoleDescription = userRoleDescription;
		this.createby = createby;
		this.cretatedate = cretatedate;
		this.isdeleted = isdeleted;
	}

	public Integer getUserRoleId() {
		return this.userRoleId;
	}

	public void setUserRoleId(Integer userRoleId) {
		this.userRoleId = userRoleId;
	}

	public String getUserRoleName() {
		return this.userRoleName;
	}

	public void setUserRoleName(String userRoleName) {
		this.userRoleName = userRoleName;
	}

	public String getUserRoleDescription() {
		return this.userRoleDescription;
	}

	public void setUserRoleDescription(String userRoleDescription) {
		this.userRoleDescription = userRoleDescription;
	}

	public Integer getCreateby() {
		return this.createby;
	}

	public void setCreateby(Integer createby) {
		this.createby = createby;
	}

	public Date getCretatedate() {
		return this.cretatedate;
	}

	public void setCretatedate(Date cretatedate) {
		this.cretatedate = cretatedate;
	}

	public Integer getIsdeleted() {
		return this.isdeleted;
	}

	public void setIsdeleted(Integer isdeleted) {
		this.isdeleted = isdeleted;
	}

}
