package src.main.java.booking;
// Generated Sep 28, 2019, 5:11:06 PM by Hibernate Tools 5.2.12.Final

/**
 * AdminHome generated by hbm2java
 */
public class AdminHome implements java.io.Serializable {

	private String idadmin;
	private Quanly quanly;
	private String username;
	private int password;
	private String email;

	public AdminHome() {
	}

	public AdminHome(String idadmin, Quanly quanly, String username, int password, String email) {
		this.idadmin = idadmin;
		this.quanly = quanly;
		this.username = username;
		this.password = password;
		this.email = email;
	}

	public String getIdadmin() {
		return this.idadmin;
	}

	public void setIdadmin(String idadmin) {
		this.idadmin = idadmin;
	}

	public Quanly getQuanly() {
		return this.quanly;
	}

	public void setQuanly(Quanly quanly) {
		this.quanly = quanly;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public int getPassword() {
		return this.password;
	}

	public void setPassword(int password) {
		this.password = password;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

}
