package src.main.java.booking;
// Generated Aug 24, 2019, 7:47:20 PM by Hibernate Tools 5.2.12.Final

/**
 * Hoadonphong generated by hbm2java
 */
public class Hoadonphong implements java.io.Serializable {

	private HoadonphongId id;
	private Khachhang khachhang;
	private Phong phong;

	public Hoadonphong() {
	}

	public Hoadonphong(HoadonphongId id) {
		this.id = id;
	}

	public Hoadonphong(HoadonphongId id, Khachhang khachhang, Phong phong) {
		this.id = id;
		this.khachhang = khachhang;
		this.phong = phong;
	}

	public HoadonphongId getId() {
		return this.id;
	}

	public void setId(HoadonphongId id) {
		this.id = id;
	}

	public Khachhang getKhachhang() {
		return this.khachhang;
	}

	public void setKhachhang(Khachhang khachhang) {
		this.khachhang = khachhang;
	}

	public Phong getPhong() {
		return this.phong;
	}

	public void setPhong(Phong phong) {
		this.phong = phong;
	}

}
