package src.main.java.booking;
// Generated Aug 24, 2019, 7:47:20 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;

/**
 * HoadonphongId generated by hbm2java
 */
public class HoadonphongId implements java.io.Serializable {

	private String usernamekhachhang;
	private Integer sophong;
	private Integer tongtien;
	private Date ngaylayphong;
	private Date ngaytraphong;

	public HoadonphongId() {
	}

	public HoadonphongId(String usernamekhachhang, Integer sophong, Integer tongtien, Date ngaylayphong,
			Date ngaytraphong) {
		this.usernamekhachhang = usernamekhachhang;
		this.sophong = sophong;
		this.tongtien = tongtien;
		this.ngaylayphong = ngaylayphong;
		this.ngaytraphong = ngaytraphong;
	}

	public String getUsernamekhachhang() {
		return this.usernamekhachhang;
	}

	public void setUsernamekhachhang(String usernamekhachhang) {
		this.usernamekhachhang = usernamekhachhang;
	}

	public Integer getSophong() {
		return this.sophong;
	}

	public void setSophong(Integer sophong) {
		this.sophong = sophong;
	}

	public Integer getTongtien() {
		return this.tongtien;
	}

	public void setTongtien(Integer tongtien) {
		this.tongtien = tongtien;
	}

	public Date getNgaylayphong() {
		return this.ngaylayphong;
	}

	public void setNgaylayphong(Date ngaylayphong) {
		this.ngaylayphong = ngaylayphong;
	}

	public Date getNgaytraphong() {
		return this.ngaytraphong;
	}

	public void setNgaytraphong(Date ngaytraphong) {
		this.ngaytraphong = ngaytraphong;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HoadonphongId))
			return false;
		HoadonphongId castOther = (HoadonphongId) other;

		return ((this.getUsernamekhachhang() == castOther.getUsernamekhachhang())
				|| (this.getUsernamekhachhang() != null && castOther.getUsernamekhachhang() != null
						&& this.getUsernamekhachhang().equals(castOther.getUsernamekhachhang())))
				&& ((this.getSophong() == castOther.getSophong()) || (this.getSophong() != null
						&& castOther.getSophong() != null && this.getSophong().equals(castOther.getSophong())))
				&& ((this.getTongtien() == castOther.getTongtien()) || (this.getTongtien() != null
						&& castOther.getTongtien() != null && this.getTongtien().equals(castOther.getTongtien())))
				&& ((this.getNgaylayphong() == castOther.getNgaylayphong())
						|| (this.getNgaylayphong() != null && castOther.getNgaylayphong() != null
								&& this.getNgaylayphong().equals(castOther.getNgaylayphong())))
				&& ((this.getNgaytraphong() == castOther.getNgaytraphong())
						|| (this.getNgaytraphong() != null && castOther.getNgaytraphong() != null
								&& this.getNgaytraphong().equals(castOther.getNgaytraphong())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUsernamekhachhang() == null ? 0 : this.getUsernamekhachhang().hashCode());
		result = 37 * result + (getSophong() == null ? 0 : this.getSophong().hashCode());
		result = 37 * result + (getTongtien() == null ? 0 : this.getTongtien().hashCode());
		result = 37 * result + (getNgaylayphong() == null ? 0 : this.getNgaylayphong().hashCode());
		result = 37 * result + (getNgaytraphong() == null ? 0 : this.getNgaytraphong().hashCode());
		return result;
	}

}
