package src.main.java.booking;
// Generated Sep 28, 2019, 5:11:06 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Khachhang generated by hbm2java
 */
public class Khachhang implements java.io.Serializable {

	private String usernamekhachhang;
	private int passwordkhachhang;
	private String emailkhachhang;
	private int idkhachhang;
	private Set hoadonphongs = new HashSet(0);

	public Khachhang() {
	}

	public Khachhang(int passwordkhachhang, String emailkhachhang, int idkhachhang) {
		this.passwordkhachhang = passwordkhachhang;
		this.emailkhachhang = emailkhachhang;
		this.idkhachhang = idkhachhang;
	}

	public Khachhang(int passwordkhachhang, String emailkhachhang, int idkhachhang, Set hoadonphongs) {
		this.passwordkhachhang = passwordkhachhang;
		this.emailkhachhang = emailkhachhang;
		this.idkhachhang = idkhachhang;
		this.hoadonphongs = hoadonphongs;
	}

	public String getUsernamekhachhang() {
		return this.usernamekhachhang;
	}

	public void setUsernamekhachhang(String usernamekhachhang) {
		this.usernamekhachhang = usernamekhachhang;
	}

	public int getPasswordkhachhang() {
		return this.passwordkhachhang;
	}

	public void setPasswordkhachhang(int passwordkhachhang) {
		this.passwordkhachhang = passwordkhachhang;
	}

	public String getEmailkhachhang() {
		return this.emailkhachhang;
	}

	public void setEmailkhachhang(String emailkhachhang) {
		this.emailkhachhang = emailkhachhang;
	}

	public int getIdkhachhang() {
		return this.idkhachhang;
	}

	public void setIdkhachhang(int idkhachhang) {
		this.idkhachhang = idkhachhang;
	}

	public Set getHoadonphongs() {
		return this.hoadonphongs;
	}

	public void setHoadonphongs(Set hoadonphongs) {
		this.hoadonphongs = hoadonphongs;
	}

}
