package src.main.java.booking;
// Generated Oct 5, 2019, 3:25:22 PM by Hibernate Tools 5.4.3.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Phong generated by hbm2java
 */
public class Phong implements java.io.Serializable {

	private int sophong;
	private String namephong;
	private String typephong;
	private String giaphong;
	private Set hoadonphongs = new HashSet(0);

	public Phong() {
	}

	public Phong(int sophong, String namephong) {
		this.sophong = sophong;
		this.namephong = namephong;
	}

	public Phong(int sophong, String namephong, String typephong, String giaphong, Set hoadonphongs) {
		this.sophong = sophong;
		this.namephong = namephong;
		this.typephong = typephong;
		this.giaphong = giaphong;
		this.hoadonphongs = hoadonphongs;
	}

	public int getSophong() {
		return this.sophong;
	}

	public void setSophong(int sophong) {
		this.sophong = sophong;
	}

	public String getNamephong() {
		return this.namephong;
	}

	public void setNamephong(String namephong) {
		this.namephong = namephong;
	}

	public String getTypephong() {
		return this.typephong;
	}

	public void setTypephong(String typephong) {
		this.typephong = typephong;
	}

	public String getGiaphong() {
		return this.giaphong;
	}

	public void setGiaphong(String giaphong) {
		this.giaphong = giaphong;
	}

	public Set getHoadonphongs() {
		return this.hoadonphongs;
	}

	public void setHoadonphongs(Set hoadonphongs) {
		this.hoadonphongs = hoadonphongs;
	}

}
