package src.main.java.booking;
// Generated Sep 28, 2019, 5:11:06 PM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Quanly generated by hbm2java
 */
public class Quanly implements java.io.Serializable {

	private String idquanly;
	private String usernamequanly;
	private int passwordquanly;
	private String emailquanly;
	private Set adminHomes = new HashSet(0);

	public Quanly() {
	}

	public Quanly(String idquanly, String usernamequanly, int passwordquanly, String emailquanly) {
		this.idquanly = idquanly;
		this.usernamequanly = usernamequanly;
		this.passwordquanly = passwordquanly;
		this.emailquanly = emailquanly;
	}

	public Quanly(String idquanly, String usernamequanly, int passwordquanly, String emailquanly, Set adminHomes) {
		this.idquanly = idquanly;
		this.usernamequanly = usernamequanly;
		this.passwordquanly = passwordquanly;
		this.emailquanly = emailquanly;
		this.adminHomes = adminHomes;
	}

	public String getIdquanly() {
		return this.idquanly;
	}

	public void setIdquanly(String idquanly) {
		this.idquanly = idquanly;
	}

	public String getUsernamequanly() {
		return this.usernamequanly;
	}

	public void setUsernamequanly(String usernamequanly) {
		this.usernamequanly = usernamequanly;
	}

	public int getPasswordquanly() {
		return this.passwordquanly;
	}

	public void setPasswordquanly(int passwordquanly) {
		this.passwordquanly = passwordquanly;
	}

	public String getEmailquanly() {
		return this.emailquanly;
	}

	public void setEmailquanly(String emailquanly) {
		this.emailquanly = emailquanly;
	}

	public Set getAdminHomes() {
		return this.adminHomes;
	}

	public void setAdminHomes(Set adminHomes) {
		this.adminHomes = adminHomes;
	}

}
