package src.main.java.booking;
// Generated Aug 24, 2019, 7:47:20 PM by Hibernate Tools 5.2.12.Final

/**
 * Quanly generated by hbm2java
 */
public class Quanly implements java.io.Serializable {

	private String idquanly;
	private String usernamequanly;
	private int passwordquanly;
	private String emailquanly;

	public Quanly() {
	}

	public Quanly(String idquanly, String usernamequanly, int passwordquanly, String emailquanly) {
		this.idquanly = idquanly;
		this.usernamequanly = usernamequanly;
		this.passwordquanly = passwordquanly;
		this.emailquanly = emailquanly;
	}

	public String getIdquanly() {
		return this.idquanly;
	}

	public void setIdquanly(String idquanly) {
		this.idquanly = idquanly;
	}

	public String getUsernamequanly() {
		return this.usernamequanly;
	}

	public void setUsernamequanly(String usernamequanly) {
		this.usernamequanly = usernamequanly;
	}

	public int getPasswordquanly() {
		return this.passwordquanly;
	}

	public void setPasswordquanly(int passwordquanly) {
		this.passwordquanly = passwordquanly;
	}

	public String getEmailquanly() {
		return this.emailquanly;
	}

	public void setEmailquanly(String emailquanly) {
		this.emailquanly = emailquanly;
	}

}
