package src.main.java.booking;
// Generated Oct 1, 2019, 11:56:01 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;

/**
 * ServiceType generated by hbm2java
 */
public class ServiceType implements java.io.Serializable {

	private Integer serviceId;
	private String serviceName;
	private String serviceCode;
	private String serviceDescription;
	private Integer createby;
	private Date cretatedate;
	private Integer isdeleted;

	public ServiceType() {
	}

	public ServiceType(String serviceName, String serviceCode, String serviceDescription) {
		this.serviceName = serviceName;
		this.serviceCode = serviceCode;
		this.serviceDescription = serviceDescription;
	}

	public ServiceType(String serviceName, String serviceCode, String serviceDescription, Integer createby,
			Date cretatedate, Integer isdeleted) {
		this.serviceName = serviceName;
		this.serviceCode = serviceCode;
		this.serviceDescription = serviceDescription;
		this.createby = createby;
		this.cretatedate = cretatedate;
		this.isdeleted = isdeleted;
	}

	public Integer getServiceId() {
		return this.serviceId;
	}

	public void setServiceId(Integer serviceId) {
		this.serviceId = serviceId;
	}

	public String getServiceName() {
		return this.serviceName;
	}

	public void setServiceName(String serviceName) {
		this.serviceName = serviceName;
	}

	public String getServiceCode() {
		return this.serviceCode;
	}

	public void setServiceCode(String serviceCode) {
		this.serviceCode = serviceCode;
	}

	public String getServiceDescription() {
		return this.serviceDescription;
	}

	public void setServiceDescription(String serviceDescription) {
		this.serviceDescription = serviceDescription;
	}

	public Integer getCreateby() {
		return this.createby;
	}

	public void setCreateby(Integer createby) {
		this.createby = createby;
	}

	public Date getCretatedate() {
		return this.cretatedate;
	}

	public void setCretatedate(Date cretatedate) {
		this.cretatedate = cretatedate;
	}

	public Integer getIsdeleted() {
		return this.isdeleted;
	}

	public void setIsdeleted(Integer isdeleted) {
		this.isdeleted = isdeleted;
	}

}
