package src.main.java.booking;
// Generated Oct 5, 2019, 3:25:22 PM by Hibernate Tools 5.4.3.Final

import java.util.Date;

/**
 * ServiceAddress generated by hbm2java
 */
public class ServiceAddress implements java.io.Serializable {

	private Integer addressId;
	private String address1;
	private String address2;
	private String addressCity;
	private String addressZipcode;
	private Integer createby;
	private Date cretatedate;
	private Integer isdeleted;

	public ServiceAddress() {
	}

	public ServiceAddress(String address1, String addressCity) {
		this.address1 = address1;
		this.addressCity = addressCity;
	}

	public ServiceAddress(String address1, String address2, String addressCity, String addressZipcode, Integer createby,
			Date cretatedate, Integer isdeleted) {
		this.address1 = address1;
		this.address2 = address2;
		this.addressCity = addressCity;
		this.addressZipcode = addressZipcode;
		this.createby = createby;
		this.cretatedate = cretatedate;
		this.isdeleted = isdeleted;
	}

	public Integer getAddressId() {
		return this.addressId;
	}

	public void setAddressId(Integer addressId) {
		this.addressId = addressId;
	}

	public String getAddress1() {
		return this.address1;
	}

	public void setAddress1(String address1) {
		this.address1 = address1;
	}

	public String getAddress2() {
		return this.address2;
	}

	public void setAddress2(String address2) {
		this.address2 = address2;
	}

	public String getAddressCity() {
		return this.addressCity;
	}

	public void setAddressCity(String addressCity) {
		this.addressCity = addressCity;
	}

	public String getAddressZipcode() {
		return this.addressZipcode;
	}

	public void setAddressZipcode(String addressZipcode) {
		this.addressZipcode = addressZipcode;
	}

	public Integer getCreateby() {
		return this.createby;
	}

	public void setCreateby(Integer createby) {
		this.createby = createby;
	}

	public Date getCretatedate() {
		return this.cretatedate;
	}

	public void setCretatedate(Date cretatedate) {
		this.cretatedate = cretatedate;
	}

	public Integer getIsdeleted() {
		return this.isdeleted;
	}

	public void setIsdeleted(Integer isdeleted) {
		this.isdeleted = isdeleted;
	}

}
